from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

servico = Service(ChromeDriverManager().install())

navegador = webdriver.Chrome(service=servico)

navegador.get('https://buscacepinter.correios.com.br/app/endereco/index.php?t')
navegador.save_screenshot("open0.png")
navegador.maximize_window()
navegador.save_screenshot("open1.png")
navegador.find_element('xpath', '//*[@id="endereco"]').click()
navegador.save_screenshot("open2.png")
navegador.find_element('xpath', '//*[@id="endereco"]').send_keys('80700000')
navegador.save_screenshot("open3.png")
navegador.find_element('xpath', '//*[@id="btn_pesquisar"]').click()
navegador.save_screenshot("open4.png")
navegador.find_element('xpath', '//*[@id="mensagem-resultado"]')
navegador.save_screenshot("open5.png")
navegador.find_element('xpath', '//*[@id="btn_nbusca"]').click()
navegador.save_screenshot("open6.png")
navegador.find_element('xpath','//*[@id="endereco"]').click()
navegador.save_screenshot("open7.png")
navegador.find_element('xpath', '//*[@id="endereco"]').send_keys('01013-001')
navegador.save_screenshot("open8.png")
navegador.find_element('xpath', '//*[@id="btn_pesquisar"]').click()
navegador.save_screenshot("open9.png")
navegador.find_element('xpath', '//*[@id="resultado-DNEC"]/tbody/tr/td[1]')
navegador.save_screenshot("open10.png")
navegador.find_element('xpath', '//*[@id="menu"]/a[2]').click()
navegador.save_screenshot("open11.png")
navegador.find_element('xpath', '//*[@id="carol-fecha"]').click()
navegador.save_screenshot("open12.png")
navegador.find_element('xpath', '//*[@id="btnCookie"]').click()
navegador.save_screenshot("open13.png")
navegador.get('https://rastreamento.correios.com.br/app/index.php')
navegador.save_screenshot("open14.png")
navegador.find_element('xpath', '//*[@id="objeto"]').send_keys('SS987654321BR')
navegador.save_screenshot("open15.png")
navegador.find_element('xpath', '//*[@id="b-pesquisar"]').click()
navegador.find_element('xpath', '/html/body/main/div[1]/form/div[2]/div[2]/div[2]/div[3]')
navegador.save_screenshot("open16.png")
navegador.find_element('xpath', '//*[@id="menu"]/a[2]').click()
navegador.find_element('xpath', '//*[@id="menu-content"]/div/div/ul[2]/li/a/img')
navegador.save_screenshot("open17.png")
navegador.close()